### ISSUE TITLE
Coins stuck in wallet

### ISSUE THREAD

**Issue by LastDragoon** [terracoin/TRCpay#2]
You can recieve but not send

**Comment by TheSin-** [comment]
you are likely on a split, what version of the client are you using?  Make sure you are on the latest version if it's 0.12.1.5 or less you need to upgrade.

**Comment by TheSin-** [comment]
Also git is for code issues, please use the official discord for support type help.

**Comment by LastDragoon** [comment]
its the TRC Pay in android and in ios both not wurking ,you can recieve coins to the adres but not send

happy you stil are around i knew it ;) in the dicord no one knows ;) come join us again m8 after cryptopia i did not have good feeling about coins  i try to get private key but failing to decrypt that i dont know if its posebil to send it to paper wallet or electrum trough private key
